import fs from 'node:fs/promises';
import ts from 'typescript';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
const dir=new URL('../.test-data/modules/',import.meta.url);await fs.mkdir(dir,{recursive:true});
for(const name of ['movies','query','demo']){const source=await fs.readFile(new URL(`../lib/${name}.ts`,import.meta.url),'utf8');const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replaceAll("'./movies'","'./movies.js'");await fs.writeFile(new URL(name+'.js',dir),out);}
const {defaultFilters,filtersSchema,evaluateMovie,sortMovies}=await import(new URL('movies.js',dir));const {catalogQuery}=await import(new URL('query.js',dir));const {demoMovies}=await import(new URL('demo.js',dir));
const unknown={...structuredClone(demoMovies[0]),id:999,title:'Unknown fields',scores:{critics:null,audience:null,imdb:null},guidance:{},certification:null,runtime:null,year:null};
const db=new DatabaseSync(':memory:');db.exec(await fs.readFile(new URL('../migrations/001_initial.sql',import.meta.url),'utf8'));const fixtures=[...demoMovies,unknown];for(const m of fixtures)db.prepare('INSERT INTO movies(id,title,data,updated_at) VALUES(?,?,?,?)').run(m.id,m.title,JSON.stringify(m),Date.now());
const cases=[{}, {critics:[0,40]}, {critics:[80,null]}, {critics:[null,40]}, {audience:[90,null]}, {imdb:[null,8]}, {content:{violence:[3]}}, {content:{violence:[0,1]}}, {presence:{nudity:'present'}}, {presence:{nudity:'absent'}}, {content:{frightening:[0]}}, {content:{frightening:[0]},includeUnknown:true}, {certifications:['R','NC-17']}, {certifications:['R'],includeUnknown:true}, {actors:[{id:1532,name:'Bill Murray'},{id:5469,name:'Ralph Fiennes'}],actorMode:'all'}, {actors:[{id:1532,name:'Bill Murray'},{id:5469,name:'Ralph Fiennes'}],actorMode:'any'}, {directors:[{id:5655,name:'Wes Anderson'}]}, {runtime:[null,90]}, {year:[2010,null]}, {query:'Budapest'}, {query:"' OR 1=1 --"}, {genres:['Animation']}, {language:'fr'}, {content:{violence:[3]},critics:[null,40],presence:{nudity:'absent'}}, {content:{nudity:[0]},presence:{nudity:'present'}}];
let checked=0;for(const example of cases){for(const includeUnknown of [false,true]){const f=filtersSchema.parse({...example,includeUnknown});const q=catalogQuery(f);const actual=db.prepare('SELECT id FROM movies'+q.where+q.order).all(...q.values).map(x=>x.id).sort();const expected=fixtures.filter(m=>evaluateMovie(m,f)).map(m=>m.id).sort();assert.deepEqual(actual,expected,JSON.stringify(f));checked++;}}
assert.equal(evaluateMovie(unknown,filtersSchema.parse({presence:{nudity:'absent'}})),null);assert.equal(evaluateMovie(unknown,filtersSchema.parse({content:{violence:[0]}})),null);
assert.equal(filtersSchema.safeParse({critics:[80,20]}).success,false);assert.equal(filtersSchema.safeParse({imdb:[0,11]}).success,false);assert.equal(filtersSchema.safeParse({content:{nudity:[11]}}).success,false);
for(const sort of ['critics-low','critics-high','imdb-low','oldest','newest','runtime']){const f=filtersSchema.parse({sort});const q=catalogQuery(f);const actual=db.prepare('SELECT id FROM movies'+q.where+q.order).all(...q.values).map(x=>x.id);const expected=[...fixtures].sort((a,b)=>sortMovies(a,b,sort)).map(x=>x.id);assert.deepEqual(actual,expected);checked++;}
// SQLite atomically claims a job only once, including concurrent requests.
const now=Date.now();db.prepare("INSERT INTO jobs(movie_id,status,attempts,next_attempt,lease_until,updated_at) VALUES(1,'queued',0,0,0,?)").run(now);const claim=db.prepare("UPDATE jobs SET status='running',lease_until=?,attempts=attempts+1 WHERE movie_id=? AND ((status IN ('queued','failed') AND next_attempt<=? AND attempts<4) OR (status='running' AND lease_until<?)) RETURNING attempts");assert.equal(claim.get(now+60000,1,now,now).attempts,1);assert.equal(claim.get(now+60000,1,now,now),undefined);assert.equal(claim.get(now+120001,1,now+60001,now+60001).attempts,2);
console.log(`PASS: ${checked} filter/sort parity checks, unknown handling, input bounds, injection handling, and job lease recovery.`);
