import { database } from './db.js';
import { collectMovie, tmdb } from './providers.js';
import { Movie, Filters, evaluateMovie } from '../lib/movies.js';
import { catalogQuery } from '../lib/query.js';
export async function getMovie(id:number):Promise<Movie|null>{const row=await database().prepare('SELECT data FROM movies WHERE id=?').bind(id).first<{data:string}>();return row?JSON.parse(row.data):null;}
export async function findMovies(f:Filters){const {where,values,order}=catalogQuery(f);const db=database();const [count,rows]=await Promise.all([db.prepare('SELECT COUNT(*) as count FROM movies'+where).bind(...values).first<{count:number}>(),db.prepare('SELECT data FROM movies'+where+order+' LIMIT 24 OFFSET ?').bind(...values,(f.page-1)*24).all<{data:string}>()]);return {total:count?.count||0,results:rows.results.map(r=>evaluateMovie(JSON.parse(r.data),f)).filter(Boolean)};}
export async function enqueue(id:number,background=false){const db=database();const now=Date.now();const movie=await getMovie(id);if(movie&&now-Date.parse(movie.updatedAt)<86400000)return {status:'cached',movie};await db.prepare("INSERT INTO jobs(movie_id,status,attempts,next_attempt,lease_until,updated_at) VALUES(?,'queued',0,0,0,?) ON CONFLICT(movie_id) DO UPDATE SET status='queued', attempts=0, next_attempt=0, updated_at=excluded.updated_at WHERE jobs.status IN ('complete','partial') OR (jobs.status='failed' AND jobs.next_attempt<=?)").bind(id,now,now).run();await db.prepare("UPDATE jobs SET background=? WHERE movie_id=? AND status='queued'").bind(background?1:0,id).run();return {status:'queued',movie};}
export async function processJob(id:number){const db=database();const now=Date.now();const claim=await db.prepare("UPDATE jobs SET status='running',lease_until=?,attempts=attempts+1,updated_at=? WHERE movie_id=? AND ((status IN ('queued','failed') AND next_attempt<=? AND attempts<4) OR (status='running' AND lease_until<?)) RETURNING attempts,background").bind(now+60000,now,id,now,now).first<{attempts:number;background:number}>();if(!claim)return;try{const {movie,issues}=await collectMovie(id,await getMovie(id),!!claim.background);await db.batch([db.prepare('INSERT INTO movies(id,title,data,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,data=excluded.data,updated_at=excluded.updated_at').bind(id,movie.title,JSON.stringify(movie),Date.now()),db.prepare('UPDATE jobs SET status=?,error=?,lease_until=0,updated_at=?,next_attempt=? WHERE movie_id=?').bind(issues.length?(claim.attempts<4?'failed':'partial'):'complete',issues.join(' ')||null,Date.now(),Date.now()+60000*2**claim.attempts,id)]);}catch(e){await db.prepare("UPDATE jobs SET status='failed',error=?,next_attempt=?,lease_until=0,updated_at=? WHERE movie_id=?").bind(e instanceof Error?e.message:'Unable to retrieve this movie.',Date.now()+Math.min(3600000,60000*2**claim.attempts),Date.now(),id).run();}}
export async function daily(){const db=database();const day=new Intl.DateTimeFormat('en-CA',{timeZone:process.env.TZ||'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());let run=await db.prepare('SELECT * FROM runs WHERE day=?').bind(day).first<{status:string;ids:string;updated_at:number}>();if(run?.status==='complete')return {status:'already_complete',ids:JSON.parse(run.ids)};if(run?.status==='running'&&Date.now()-run.updated_at<180000)return {status:'running'};const claim=await db.prepare("INSERT INTO runs(day,status,ids,updated_at) VALUES(?,'running','[]',?) ON CONFLICT(day) DO UPDATE SET status='running',updated_at=excluded.updated_at WHERE runs.status!='complete' AND (runs.status!='running' OR runs.updated_at<?) RETURNING day").bind(day,Date.now(),Date.now()-180000).first();if(!claim)return {status:'running'};
 try{let ids:number[]=run?JSON.parse(run.ids):[];if(!ids.length){const list=await tmdb('movie/popular',{language:'en-US',region:'US'});ids=list.results.slice(0,10).map((m:any)=>m.id);await db.prepare('UPDATE runs SET ids=? WHERE day=?').bind(JSON.stringify(ids),day).run();}for(let i=0;i<ids.length;i+=2)await Promise.all(ids.slice(i,i+2).map(async id=>{if(await getMovie(id))return;await enqueue(id,true);await processJob(id);}));const pending=await db.prepare("SELECT movie_id,status FROM jobs WHERE movie_id IN ("+ids.map(()=>'?').join(',')+") AND status NOT IN ('complete','partial')").bind(...ids).all();const status=pending.results.length?'partial':'complete';await db.prepare('UPDATE runs SET status=?,updated_at=? WHERE day=?').bind(status,Date.now(),day).run();return {status,ids,pending:pending.results};}catch(e){await db.prepare("UPDATE runs SET status='failed',updated_at=? WHERE day=?").bind(Date.now(),day).run();throw e;}}
