import { Movie, Category } from './movies.js';
const evidence={source:'Illustrative preview',url:'',checkedAt:'',note:'Sample values for testing filters. Not verified movie guidance or current ratings.'};
const guidance=(data:Partial<Record<Category,number>>)=>Object.fromEntries(Object.entries(data).map(([k,v])=>[k,{...evidence,level:v===undefined?null:[0,3,6,10][v],scaleMax:10 as const,present:v!==0,description:'Illustrative value only. Connect a content provider for verified guidance.'}]));
// Deliberately separate from the persistent catalog. Never import these sample ratings.
export const demoMovies:Movie[]=[
 {id:120467,title:'The Grand Budapest Hotel',year:2014,runtime:99,certification:'R',poster:'assets/grand-budapest.png',overview:'A legendary concierge and his young lobby boy become entangled in a stolen painting and a family fortune.',genres:['Comedy','Adventure'],language:'en',cast:[{id:5469,name:'Ralph Fiennes'},{id:1532,name:'Bill Murray'}],directors:[{id:5655,name:'Wes Anderson'}],popularity:90,imdbId:null,scores:{critics:92,audience:87,imdb:8.1},scoreEvidence:{critics:evidence,audience:evidence,imdb:evidence},guidance:guidance({violence:2,nudity:1,sex:1,profanity:3,substances:1,frightening:2}),source:evidence,updatedAt:'',sample:true},
 {id:83666,title:'Moonrise Kingdom',year:2012,runtime:94,certification:'PG-13',poster:'assets/moonrise.jpg',overview:'Two young pen pals run away together on a New England island, setting an eccentric search party in motion.',genres:['Comedy','Drama','Romance'],language:'en',cast:[{id:1532,name:'Bill Murray'},{id:819,name:'Edward Norton'},{id:62,name:'Bruce Willis'}],directors:[{id:5655,name:'Wes Anderson'}],popularity:80,imdbId:null,scores:{critics:93,audience:86,imdb:7.8},scoreEvidence:{critics:evidence,audience:evidence,imdb:evidence},guidance:guidance({violence:1,nudity:0,sex:1,profanity:1,substances:1,frightening:1}),source:evidence,updatedAt:'',sample:true},
 {id:10315,title:'Fantastic Mr. Fox',year:2009,runtime:87,certification:'PG',poster:'assets/fantastic-fox.jpg',overview:'An irrepressible fox returns to his chicken-stealing ways and leads his woodland neighbors into a showdown with three farmers.',genres:['Animation','Comedy','Adventure'],language:'en',cast:[{id:1461,name:'George Clooney'},{id:5064,name:'Meryl Streep'},{id:1532,name:'Bill Murray'}],directors:[{id:5655,name:'Wes Anderson'}],popularity:70,imdbId:null,scores:{critics:35,audience:91,imdb:null},scoreEvidence:{critics:evidence,audience:evidence},guidance:guidance({violence:3,nudity:0,sex:0,profanity:0,substances:1}),source:evidence,updatedAt:'',sample:true}
];
